name: retrofit_flutter
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  dio: ^5.3.3
  retrofit: '>=4.0.0 <5.0.0'
  logger: any  #for logging purpose
  json_annotation: ^4.8.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: '>=7.0.0 <8.0.0'   
  build_runner: '>=2.3.0 <4.0.0'
  json_serializable: ^6.6.2

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
